### ISSUE TITLE
The radio and check indicators are not aligned properly.

### ISSUE THREAD

**Issue by NMyVision** [DesignRevision/shards-dashboard#1]
The radio and check indicators are not aligned properly, the problem occurs on screen widths greater than 1200px.

**Comment by hisk** [comment]
@NMyVision Thanks a lot for taking the time to submit this Matt! 🙇I'll include this in the next update.

**Comment by ramon-src** [comment]
@hisk are you not aligned yet? Can I do it?

**Comment by hisk** [comment]
@ramon-src Sure, go ahead! 👍Thanks!

**Comment by ramon-src** [comment]
@hisk I found the problem... 
We have a media query on html tag which has font-size as 18px. 
The custom checkbox was created by javascript?

**Comment by hisk** [comment]
@ramon-src The custom checkboxes are inherited from [Shards](https://github.com/DesignRevision/shards-ui) and the [media query](https://github.com/DesignRevision/shards-dashboard/blob/master/styles/scss/_reboot.scss#L9) was included to adjust the font sizes on larger screens. While that's a nice touch, I think the overhead added by re-adjusting the custom controls is just not worth it and I think it's best to just remove the media query for now.
