### ISSUE TITLE
Quill Editor does not visually reflect <strong> content

### ISSUE THREAD

**Issue by TDodgeCo** [DesignRevision/shards-dashboard#3]
Hi!

I'm using Shards-UI 2.0.3.

When I write content inside the quill editor found in `add-new-post.html`, I cannot get the `bold` content to show up visually inside the editor. It just looks the same as all of the other content.

When I inspect the text, it is definitely being wrapped with the `<strong>` tag. It's just not reflected within the editor itself.

I have made no changes to the `js` or `scss` anywhere in the template.

Is there a scss class hidden somewhere that is responsible for this? 

Thanks in advance for your help.

Here's some screenshots in case I wasn't able to communicate clearly what my issue is.

https://i.imgur.com/VAlUzsF.png

https://i.imgur.com/ez3scPM.png

EDIT: I realize I didn't show a comparison between the emboldened text and non-emboldened text.. I assure though, they look the same.

**Comment by hisk** [comment]
@TDodgeCo Great find! Thank you so much for taking the time to submit this Tim! 😁

**Comment by TDodgeCo** [comment]
any word on this @hisk?

**Comment by hisk** [comment]
@TDodgeCo Done! Sorry for the huge delay. 😁
