### ISSUE TITLE
Provide Documentation for how to integrate for Angular6 App

### ISSUE THREAD

**Issue by BMLande** [DesignRevision/shards-dashboard#7]

**Comment by BMLande** [comment]
I am trying to use this in angular6 app , everything is working fine , but datepicker other functionalities are not behaving well ,can you please provide any documentation for angular6 app integration .
i having issues in adding SCSS files . please reply ASAP .
thanks

**Comment by nickvasdev** [comment]
@BMLande I'm afraid that Shards Dashboard is not optimized for Angular 6 and would require heavy customizations in order to adjust the missing components (such as the datepickers, etc). The official Angular 6 version is something I plan on developing, however there's no ETA just yet. 🙂

**Comment by BMLande** [comment]
Thanks , I will be waiting for angular release.
