### ISSUE TITLE
Imported file missing ?

### ISSUE THREAD

**Issue by migmake** [DesignRevision/shards-dashboard#9]
In the file styles/scss/shards-dashboards.scss there is this import : 

// Base Shards UI Kit
@import "../../node_modules/shards-ui/src/scss/shards";

But I cannot find it anywhere in the pack.
![image](https://user-images.githubusercontent.com/3531623/55221883-d6e51a00-520a-11e9-970f-84c761ab5183.png)

**Comment by nickvasdev** [comment]
Please check and make sure that you do have all dependencies installed by running `npm install`. 😄

**Comment by migmake** [comment]
Hi. Thank you for answer.
OK I understand now.
But dont you think it would great to add the command "npm install shards-ui" in the quickstart section of the documentation ?
For people like me who are not used to node modules and npm :)

**Comment by nickvasdev** [comment]
You don't need to install Shards, it is already listed as an NPM dependency. Furthermore, the steps are already described in the [README.md](https://github.com/DesignRevision/shards-dashboard) file. 😄

**Comment by migmake** [comment]
OK thanks, I missed this part. I was searching an answer in the other documentation only.
